MAIN_COMMAND := make -f Makefile.gba_real
all:
	$(eval MAKE_COMMAND_ARGS := -j)
	make -C linker $(MAKE_COMMAND_ARGS)
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS)
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=ewram
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=iwram
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=vram
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=ovram

clean:
	$(eval MAKE_COMMAND_ARGS := clean)
	make -C linker $(MAKE_COMMAND_ARGS)
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS)
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=ewram
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=iwram
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=vram
	$(MAIN_COMMAND) $(MAKE_COMMAND_ARGS) ADDED_PARTICLE=ovram
