#!/bin/sh

cp -R /home/builder/pokemon_gen3_to_genx/. .

make clean
mkdir -p build
cp -R linker/ build/
ls -altr build/linker
make 2>&1 >/dev/null | grep ^$(pwd);

mkdir -p /home/builder/pokemon_gen3_to_genx/out
cp building_mb.gba /home/builder/pokemon_gen3_to_genx/out/gba_mem_viewer.gba


